### ISSUE TITLE
UMD bundle output

### ISSUE THREAD

**Issue by talmax1124** [karolis-sh/netlify-cms-widget-inline-select#26]
Hello, can you check my repository to check why it is not showing up on the netlifycms? I am using the multi-select one but it is showing me this.

My repo: https://github.com/talmax1124/knighttimesnews-restore

**Comment by karolis-sh** [comment]
Hi, you're importing components incorrectly - https://github.com/talmax1124/knighttimesnews-restore/blob/master/src/admin/index.html#L9-L10. Should be something like this - `const { InlineSelectControl, InlineSelectPreview } = require("netlify-cms-widget-inline-select");`

**Comment by talmax1124** [comment]
It is still saying the same thing @karolis-sh 
<img width="412" alt="Screen Shot 2021-09-12 at 10 27 03 PM" src="https://user-images.githubusercontent.com/61528430/133014944-6314cd81-078d-4e47-a577-4d0b1eb716d5.png">

**Comment by talmax1124** [comment]
Can you make this into a CDN? Because when I check the console it says: 

<img width="1440" alt="Screen Shot 2021-09-12 at 10 55 26 PM" src="https://user-images.githubusercontent.com/61528430/133017122-8056da5e-22b5-4e2e-a97f-ea95178ba592.png">


@karolis-sh

**Comment by karolis-sh** [comment]
> Can you make this into a CDN? Because when I check the console it says:
> 
> <img alt="Screen Shot 2021-09-12 at 10 55 26 PM" width="1440" src="https://user-images.githubusercontent.com/61528430/133017122-8056da5e-22b5-4e2e-a97f-ea95178ba592.png">
> 
> @karolis-sh

You're seeing this error because `reuqire` syntax is Node only, and Eleventy doesn't handle it differently in your setup.

Anyway this package doesn't expose UMD type module, so such script include https://github.com/talmax1124/knighttimesnews-restore/blob/master/src/admin/index.html#L9-L10 won't have affect. I might look into this later, but cannot make any promises on the timeframe.

**Comment by karolis-sh** [comment]
progress on that tracked in https://github.com/karolis-sh/netlify-cms-widget-inline-select/issues/4

**Comment by talmax1124** [comment]
Ok, thanks! If this is a CDN, it would be easier for other devs to use it as well. Just a recommendation
